# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'


variables:
- name: svc_connection
  value: svc_devtest
  

steps:
- script: |
    echo 'terraform version: '
    terraform version
    echo 'present working directory:'
    pwd
    ls -lrt
    export
  displayName: get info
       

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(svc_connection)
    backendAzureRmResourceGroupName: 'ss-rg'
    backendAzureRmStorageAccountName: 'mibtfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'demo.azure.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-lock=false -input=false'
    environmentServiceNameAzureRM: $(svc_connection)

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-lock=false -input=false'
    environmentServiceNameAzureRM: $(svc_connection)